# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgot-password-initial.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForgotPasswordWindow(object):
    def setupUi(self, ForgotPasswordWindow):
        ForgotPasswordWindow.setObjectName("ForgotPasswordWindow")
        ForgotPasswordWindow.resize(376, 613)
        ForgotPasswordWindow.setStyleSheet("    background-color: rgb(31, 149, 239);")
        self.centralwidget = QtWidgets.QWidget(ForgotPasswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendRequestButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendRequestButton.setGeometry(QtCore.QRect(130, 250, 101, 34))
        self.sendRequestButton.setStyleSheet("            QPushButton {\n"
"                border: 2px solid #8f8f91;\n"
"                border-radius: 15px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"                background-color: #dcdcdc;\n"
"                min-width: 30px; /* Đảm bảo nút là hình vuông */\n"
"                min-height: 30px; /* Đảm bảo nút là hình vuông */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #c6c6c6;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #a9a9a9;\n"
"            }")
        self.sendRequestButton.setObjectName("sendRequestButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 70, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.emailInput = QtWidgets.QLineEdit(self.centralwidget)
        self.emailInput.setGeometry(QtCore.QRect(120, 180, 151, 31))
        self.emailInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.emailInput.setObjectName("emailInput")
        ForgotPasswordWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ForgotPasswordWindow)
        self.statusbar.setObjectName("statusbar")
        ForgotPasswordWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ForgotPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ForgotPasswordWindow)

    def retranslateUi(self, ForgotPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ForgotPasswordWindow.setWindowTitle(_translate("ForgotPasswordWindow", "MainWindow"))
        self.sendRequestButton.setText(_translate("ForgotPasswordWindow", "Send Request"))
        self.label.setText(_translate("ForgotPasswordWindow", "Forgot Password "))
        self.emailInput.setPlaceholderText(_translate("ForgotPasswordWindow", "Enter your email"))
