# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(415, 626)
        LoginWindow.setStyleSheet("    background-color: rgb(31, 149, 239);")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 70, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.usernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(140, 180, 151, 31))
        self.usernameInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(140, 240, 151, 31))
        self.passwordInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(90, 310, 101, 34))
        self.loginButton.setStyleSheet("            QPushButton {\n"
"                border: 2px solid #8f8f91;\n"
"                border-radius: 15px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"                background-color: #dcdcdc;\n"
"                min-width: 30px; /* Đảm bảo nút là hình vuông */\n"
"                min-height: 30px; /* Đảm bảo nút là hình vuông */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #c6c6c6;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #a9a9a9;\n"
"            }")
        self.loginButton.setObjectName("loginButton")
        self.forgotPasswordLink = QtWidgets.QLabel(self.centralwidget)
        self.forgotPasswordLink.setGeometry(QtCore.QRect(170, 370, 81, 21))
        self.forgotPasswordLink.setToolTip("")
        self.forgotPasswordLink.setOpenExternalLinks(False)
        self.forgotPasswordLink.setObjectName("forgotPasswordLink")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(230, 310, 101, 34))
        self.registerButton.setStyleSheet("            QPushButton {\n"
"                border: 2px solid #8f8f91;\n"
"                border-radius: 15px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"                background-color: #dcdcdc;\n"
"                min-width: 30px; /* Đảm bảo nút là hình vuông */\n"
"                min-height: 30px; /* Đảm bảo nút là hình vuông */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #c6c6c6;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #a9a9a9;\n"
"            }")
        self.registerButton.setObjectName("registerButton")
        self.gridLayout.addWidget(self.centralwidget, 0, 0, 1, 1)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Login"))
        self.usernameInput.setPlaceholderText(_translate("LoginWindow", "User name"))
        self.passwordInput.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.loginButton.setText(_translate("LoginWindow", "Đăng Nhập"))
        self.forgotPasswordLink.setText(_translate("LoginWindow", "<a href=\"forgot_password\">Forgot Password</a>\n"
""))
        self.registerButton.setText(_translate("LoginWindow", "Đăng Ký"))
