# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(470, 626)
        RegisterWindow.setStyleSheet("    background-color: rgb(31, 149, 239);")
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(50, 200, 151, 31))
        self.passwordInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.forgotPasswordLink = QtWidgets.QLabel(self.centralwidget)
        self.forgotPasswordLink.setGeometry(QtCore.QRect(190, 400, 81, 21))
        self.forgotPasswordLink.setToolTip("")
        self.forgotPasswordLink.setOpenExternalLinks(False)
        self.forgotPasswordLink.setObjectName("forgotPasswordLink")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 50, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.usernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(50, 150, 151, 31))
        self.usernameInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.usernameInput.setObjectName("usernameInput")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(180, 330, 101, 34))
        self.registerButton.setStyleSheet("            QPushButton {\n"
"                border: 2px solid #8f8f91;\n"
"                border-radius: 15px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"                background-color: #dcdcdc;\n"
"                min-width: 30px; /* Đảm bảo nút là hình vuông */\n"
"                min-height: 30px; /* Đảm bảo nút là hình vuông */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #c6c6c6;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #a9a9a9;\n"
"            }")
        self.registerButton.setObjectName("registerButton")
        self.emailInput = QtWidgets.QLineEdit(self.centralwidget)
        self.emailInput.setGeometry(QtCore.QRect(250, 150, 151, 31))
        self.emailInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.emailInput.setObjectName("emailInput")
        self.phoneInput = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneInput.setGeometry(QtCore.QRect(250, 200, 151, 31))
        self.phoneInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.phoneInput.setObjectName("phoneInput")
        self.reEnterPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.reEnterPasswordInput.setGeometry(QtCore.QRect(50, 250, 151, 31))
        self.reEnterPasswordInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.reEnterPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reEnterPasswordInput.setObjectName("reEnterPasswordInput")
        self.addressInput = QtWidgets.QLineEdit(self.centralwidget)
        self.addressInput.setGeometry(QtCore.QRect(250, 250, 151, 31))
        self.addressInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.addressInput.setObjectName("addressInput")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.passwordInput.setPlaceholderText(_translate("RegisterWindow", "Password"))
        self.forgotPasswordLink.setText(_translate("RegisterWindow", "<a href=\"forgot_password\">Forgot Password</a>\n"
""))
        self.label.setText(_translate("RegisterWindow", "Register"))
        self.usernameInput.setPlaceholderText(_translate("RegisterWindow", "User name"))
        self.registerButton.setText(_translate("RegisterWindow", "Đăng Ký"))
        self.emailInput.setPlaceholderText(_translate("RegisterWindow", "Email"))
        self.phoneInput.setPlaceholderText(_translate("RegisterWindow", "Phone number"))
        self.reEnterPasswordInput.setPlaceholderText(_translate("RegisterWindow", "Re-enter Password"))
        self.addressInput.setPlaceholderText(_translate("RegisterWindow", "Address"))
