# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reset-password.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetPasswordWindow(object):
    def setupUi(self, ResetPasswordWindow):
        ResetPasswordWindow.setObjectName("ResetPasswordWindow")
        ResetPasswordWindow.resize(567, 600)
        ResetPasswordWindow.setStyleSheet("    background-color: rgb(31, 149, 239);")
        self.centralwidget = QtWidgets.QWidget(ResetPasswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.newPasswordInput.setGeometry(QtCore.QRect(190, 210, 151, 31))
        self.newPasswordInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.newPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordInput.setObjectName("newPasswordInput")
        self.resetPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetPasswordButton.setGeometry(QtCore.QRect(210, 310, 101, 34))
        self.resetPasswordButton.setStyleSheet("            QPushButton {\n"
"                border: 2px solid #8f8f91;\n"
"                border-radius: 15px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"                background-color: #dcdcdc;\n"
"                min-width: 30px; /* Đảm bảo nút là hình vuông */\n"
"                min-height: 30px; /* Đảm bảo nút là hình vuông */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #c6c6c6;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #a9a9a9;\n"
"            }")
        self.resetPasswordButton.setObjectName("resetPasswordButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 80, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.confirmationCodeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmationCodeInput.setGeometry(QtCore.QRect(190, 160, 151, 31))
        self.confirmationCodeInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.confirmationCodeInput.setObjectName("confirmationCodeInput")
        self.reEnterNewPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.reEnterNewPasswordInput.setGeometry(QtCore.QRect(190, 260, 151, 31))
        self.reEnterNewPasswordInput.setStyleSheet(" QLineEdit {\n"
"                border: 2px solid gray;\n"
"                border-radius: 10px;\n"
"                padding: 0 8px;\n"
"                background: white;\n"
"                selection-background-color: darkgray;\n"
"            }\n"
"\n"
"")
        self.reEnterNewPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.reEnterNewPasswordInput.setObjectName("reEnterNewPasswordInput")
        ResetPasswordWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ResetPasswordWindow)
        self.statusbar.setObjectName("statusbar")
        ResetPasswordWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ResetPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ResetPasswordWindow)

    def retranslateUi(self, ResetPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ResetPasswordWindow.setWindowTitle(_translate("ResetPasswordWindow", "MainWindow"))
        self.newPasswordInput.setPlaceholderText(_translate("ResetPasswordWindow", "Password"))
        self.resetPasswordButton.setText(_translate("ResetPasswordWindow", "Reset Password"))
        self.label.setText(_translate("ResetPasswordWindow", "PasswordConfirmation"))
        self.confirmationCodeInput.setPlaceholderText(_translate("ResetPasswordWindow", "confirmationCode"))
        self.reEnterNewPasswordInput.setPlaceholderText(_translate("ResetPasswordWindow", "Re-enter Password"))
