# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BaseWindow(object):
    def setupUi(self, BaseWindow):
        BaseWindow.setObjectName("BaseWindow")
        BaseWindow.resize(1121, 648)
        BaseWindow.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.centralwidget = QtWidgets.QWidget(BaseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(31, 149, 239);\n"
"}\n"
"\n"
"QPushButton {\n"
"    color:white;\n"
"    height: 30px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: #F5FAFE;\n"
"color: #1F95EF;\n"
"font-weight:bold;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/icon/profile_pic.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, 0, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboard_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.dashboard_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon/dashboard_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dashboard_1.setIcon(icon)
        self.dashboard_1.setCheckable(True)
        self.dashboard_1.setAutoExclusive(True)
        self.dashboard_1.setObjectName("dashboard_1")
        self.verticalLayout.addWidget(self.dashboard_1)
        self.profile_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.profile_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon/profile_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.profile_1.setIcon(icon1)
        self.profile_1.setCheckable(True)
        self.profile_1.setAutoExclusive(True)
        self.profile_1.setObjectName("profile_1")
        self.verticalLayout.addWidget(self.profile_1)
        self.messages_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.messages_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icon/messages_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icon/messages.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.messages_1.setIcon(icon2)
        self.messages_1.setCheckable(True)
        self.messages_1.setAutoExclusive(True)
        self.messages_1.setObjectName("messages_1")
        self.verticalLayout.addWidget(self.messages_1)
        self.notifications_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.notifications_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icon/notifications_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icon/notifications.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.notifications_1.setIcon(icon3)
        self.notifications_1.setCheckable(True)
        self.notifications_1.setAutoExclusive(True)
        self.notifications_1.setObjectName("notifications_1")
        self.verticalLayout.addWidget(self.notifications_1)
        self.settings_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.settings_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icon/settings_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icon/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.settings_1.setIcon(icon4)
        self.settings_1.setCheckable(True)
        self.settings_1.setAutoExclusive(True)
        self.settings_1.setObjectName("settings_1")
        self.verticalLayout.addWidget(self.settings_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 291, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_6 = QtWidgets.QPushButton(self.icon_only_widget)
        self.pushButton_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icon/log_out_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_name_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(31, 149, 239);\n"
"    color: #white;\n"
"}\n"
"QPushButton {\n"
"    color:white;\n"
"    text-align:left;\n"
"    height: 30px;\n"
"    border:none;\n"
"    padding-left:10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"QPushButton:checked{\n"
"background-color: #F5FAFE;\n"
"color: #1F95EF;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/icon/profile_pic.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dashboard_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.dashboard_2.setIcon(icon)
        self.dashboard_2.setCheckable(True)
        self.dashboard_2.setAutoExclusive(True)
        self.dashboard_2.setObjectName("dashboard_2")
        self.verticalLayout_2.addWidget(self.dashboard_2)
        self.profile_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.profile_2.setIcon(icon1)
        self.profile_2.setCheckable(True)
        self.profile_2.setAutoExclusive(True)
        self.profile_2.setObjectName("profile_2")
        self.verticalLayout_2.addWidget(self.profile_2)
        self.messages_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.messages_2.setIcon(icon2)
        self.messages_2.setCheckable(True)
        self.messages_2.setAutoExclusive(True)
        self.messages_2.setObjectName("messages_2")
        self.verticalLayout_2.addWidget(self.messages_2)
        self.notifications_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.notifications_2.setIcon(icon3)
        self.notifications_2.setCheckable(True)
        self.notifications_2.setAutoExclusive(True)
        self.notifications_2.setObjectName("notifications_2")
        self.verticalLayout_2.addWidget(self.notifications_2)
        self.settings_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.settings_2.setIcon(icon4)
        self.settings_2.setCheckable(True)
        self.settings_2.setAutoExclusive(True)
        self.settings_2.setObjectName("settings_2")
        self.verticalLayout_2.addWidget(self.settings_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 291, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.pushButton_11 = QtWidgets.QPushButton(self.icon_name_widget)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_menu = QtWidgets.QWidget(self.centralwidget)
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header_widget = QtWidgets.QWidget(self.main_menu)
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu = QtWidgets.QPushButton(self.header_widget)
        self.menu.setStyleSheet("border:none;")
        self.menu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icon/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu.setIcon(icon6)
        self.menu.setIconSize(QtCore.QSize(20, 20))
        self.menu.setCheckable(True)
        self.menu.setObjectName("menu")
        self.horizontalLayout_6.addWidget(self.menu)
        spacerItem2 = QtWidgets.QSpacerItem(266, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.header_widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_14 = QtWidgets.QPushButton(self.header_widget)
        self.pushButton_14.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon7)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout.addWidget(self.pushButton_14)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(266, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton_15 = QtWidgets.QPushButton(self.header_widget)
        self.pushButton_15.setStyleSheet("border:none;")
        self.pushButton_15.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icon/image (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon8)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_6.addWidget(self.pushButton_15)
        self.verticalLayout_5.addWidget(self.header_widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_menu)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard_page = QtWidgets.QWidget()
        self.dashboard_page.setObjectName("dashboard_page")
        self.groupBox_2 = QtWidgets.QGroupBox(self.dashboard_page)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 891, 571))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(460, 30, 47, 13))
        self.label_4.setObjectName("label_4")
        self.titleLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.titleLineEdit.setGeometry(QtCore.QRect(520, 30, 281, 20))
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(460, 80, 51, 16))
        self.label_5.setObjectName("label_5")
        self.contentTextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.contentTextEdit.setGeometry(QtCore.QRect(520, 80, 281, 71))
        self.contentTextEdit.setObjectName("contentTextEdit")
        self.urlLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.urlLineEdit.setGeometry(QtCore.QRect(520, 180, 281, 20))
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(460, 180, 51, 16))
        self.label_12.setObjectName("label_12")
        self.addButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addButton.setGeometry(QtCore.QRect(810, 110, 75, 23))
        self.addButton.setObjectName("addButton")
        self.editButton = QtWidgets.QPushButton(self.groupBox_2)
        self.editButton.setGeometry(QtCore.QRect(460, 530, 75, 23))
        self.editButton.setObjectName("editButton")
        self.loadButton = QtWidgets.QPushButton(self.groupBox_2)
        self.loadButton.setGeometry(QtCore.QRect(460, 450, 75, 23))
        self.loadButton.setObjectName("loadButton")
        self.postWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.postWidget.setGeometry(QtCore.QRect(10, 20, 441, 541))
        self.postWidget.setObjectName("postWidget")
        self.postWidget.setColumnCount(5)
        self.postWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.postWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.postWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.postWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.postWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.postWidget.setHorizontalHeaderItem(4, item)
        self.imageListWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.imageListWidget.setGeometry(QtCore.QRect(520, 210, 281, 192))
        self.imageListWidget.setObjectName("imageListWidget")
        self.addImageButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addImageButton.setGeometry(QtCore.QRect(590, 410, 75, 23))
        self.addImageButton.setObjectName("addImageButton")
        self.deleteButton = QtWidgets.QPushButton(self.groupBox_2)
        self.deleteButton.setGeometry(QtCore.QRect(460, 490, 75, 23))
        self.deleteButton.setObjectName("deleteButton")
        self.uploadButton = QtWidgets.QPushButton(self.groupBox_2)
        self.uploadButton.setGeometry(QtCore.QRect(680, 410, 75, 23))
        self.uploadButton.setObjectName("uploadButton")
        self.stackedWidget.addWidget(self.dashboard_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.groupBox = QtWidgets.QGroupBox(self.profile_page)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 891, 561))
        self.groupBox.setObjectName("groupBox")
        self.avatarLabel = QtWidgets.QLabel(self.groupBox)
        self.avatarLabel.setGeometry(QtCore.QRect(20, 20, 131, 131))
        self.avatarLabel.setText("")
        self.avatarLabel.setPixmap(QtGui.QPixmap(":/newPrefix/icon/profile.png"))
        self.avatarLabel.setObjectName("avatarLabel")
        self.phoneLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.phoneLineEdit.setGeometry(QtCore.QRect(10, 210, 141, 20))
        self.phoneLineEdit.setText("")
        self.phoneLineEdit.setPlaceholderText("")
        self.phoneLineEdit.setObjectName("phoneLineEdit")
        self.addressLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.addressLineEdit.setGeometry(QtCore.QRect(10, 270, 141, 20))
        self.addressLineEdit.setText("")
        self.addressLineEdit.setPlaceholderText("")
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.emailLineEdit.setGeometry(QtCore.QRect(180, 210, 141, 20))
        self.emailLineEdit.setText("")
        self.emailLineEdit.setPlaceholderText("")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.editProfileButton = QtWidgets.QPushButton(self.groupBox)
        self.editProfileButton.setGeometry(QtCore.QRect(10, 330, 81, 29))
        self.editProfileButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 7px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"    background-color: #dcdcdc;\n"
"    min-width: 15px; /* Đảm bảo nút là hình vuông */\n"
"    min-height: 15px; /* Đảm bảo nút là hình vuông */\n"
"    padding: 5px; /* Thêm khoảng cách bên trong để dễ nhấn hơn */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6c6c6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a9a9a9;\n"
"}")
        self.editProfileButton.setObjectName("editProfileButton")
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setGeometry(QtCore.QRect(130, 330, 75, 29))
        self.saveButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 7px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"    background-color: #dcdcdc;\n"
"    min-width: 15px; /* Đảm bảo nút là hình vuông */\n"
"    min-height: 15px; /* Đảm bảo nút là hình vuông */\n"
"    padding: 5px; /* Thêm khoảng cách bên trong để dễ nhấn hơn */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6c6c6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a9a9a9;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.addAvatarButton = QtWidgets.QPushButton(self.groupBox)
        self.addAvatarButton.setGeometry(QtCore.QRect(30, 160, 101, 29))
        self.addAvatarButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 7px; /* Nửa chiều rộng hoặc chiều cao của nút */\n"
"    background-color: #dcdcdc;\n"
"    min-width: 15px; /* Đảm bảo nút là hình vuông */\n"
"    min-height: 15px; /* Đảm bảo nút là hình vuông */\n"
"    padding: 5px; /* Thêm khoảng cách bên trong để dễ nhấn hơn */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c6c6c6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a9a9a9;\n"
"}")
        self.addAvatarButton.setObjectName("addAvatarButton")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 230, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(190, 230, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 290, 47, 13))
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.profile_page)
        self.messages_page = QtWidgets.QWidget()
        self.messages_page.setObjectName("messages_page")
        self.label_6 = QtWidgets.QLabel(self.messages_page)
        self.label_6.setGeometry(QtCore.QRect(300, 210, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.messages_page)
        self.notifications_page = QtWidgets.QWidget()
        self.notifications_page.setObjectName("notifications_page")
        self.groupBox_3 = QtWidgets.QGroupBox(self.notifications_page)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 891, 571))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 20, 541, 541))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.platformsWidget = QtWidgets.QWidget(self.groupBox_3)
        self.platformsWidget.setGeometry(QtCore.QRect(550, 20, 331, 131))
        self.platformsWidget.setObjectName("platformsWidget")
        self.saveButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.saveButton_2.setGeometry(QtCore.QRect(550, 220, 75, 23))
        self.saveButton_2.setObjectName("saveButton_2")
        self.postButton = QtWidgets.QPushButton(self.groupBox_3)
        self.postButton.setGeometry(QtCore.QRect(550, 260, 75, 23))
        self.postButton.setObjectName("postButton")
        self.loadDataButton = QtWidgets.QPushButton(self.groupBox_3)
        self.loadDataButton.setGeometry(QtCore.QRect(550, 180, 75, 23))
        self.loadDataButton.setObjectName("loadDataButton")
        self.stackedWidget.addWidget(self.notifications_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.label_8 = QtWidgets.QLabel(self.settings_page)
        self.label_8.setGeometry(QtCore.QRect(190, 60, 481, 331))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.settings_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.main_menu, 0, 2, 1, 1)
        BaseWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BaseWindow)
        self.statusbar.setObjectName("statusbar")
        BaseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BaseWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.menu.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.menu.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.settings_1.toggled['bool'].connect(self.settings_2.setChecked) # type: ignore
        self.notifications_1.toggled['bool'].connect(self.notifications_2.setChecked) # type: ignore
        self.messages_1.toggled['bool'].connect(self.messages_2.setChecked) # type: ignore
        self.profile_1.toggled['bool'].connect(self.profile_2.setChecked) # type: ignore
        self.dashboard_1.toggled['bool'].connect(self.dashboard_2.setChecked) # type: ignore
        self.dashboard_2.toggled['bool'].connect(self.dashboard_1.setChecked) # type: ignore
        self.profile_2.toggled['bool'].connect(self.profile_1.setChecked) # type: ignore
        self.messages_2.toggled['bool'].connect(self.messages_1.setChecked) # type: ignore
        self.notifications_2.toggled['bool'].connect(self.notifications_1.setChecked) # type: ignore
        self.settings_2.toggled['bool'].connect(self.settings_1.setChecked) # type: ignore
        self.pushButton_6.toggled['bool'].connect(BaseWindow.close) # type: ignore
        self.pushButton_11.toggled['bool'].connect(BaseWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BaseWindow)

    def retranslateUi(self, BaseWindow):
        _translate = QtCore.QCoreApplication.translate
        BaseWindow.setWindowTitle(_translate("BaseWindow", "MainWindow"))
        self.label_3.setText(_translate("BaseWindow", "Sidebar"))
        self.dashboard_2.setText(_translate("BaseWindow", "Quản lý bài viết"))
        self.profile_2.setText(_translate("BaseWindow", "Profile"))
        self.messages_2.setText(_translate("BaseWindow", "Messages"))
        self.notifications_2.setText(_translate("BaseWindow", "Quản lý bài đăng"))
        self.settings_2.setText(_translate("BaseWindow", "Settings"))
        self.pushButton_11.setText(_translate("BaseWindow", "Sign Out"))
        self.groupBox_2.setTitle(_translate("BaseWindow", "Quản lý bài viết"))
        self.label_4.setText(_translate("BaseWindow", "Tiêu đề :"))
        self.label_5.setText(_translate("BaseWindow", "Nội dung :"))
        self.label_12.setText(_translate("BaseWindow", "URL ảnh :"))
        self.addButton.setText(_translate("BaseWindow", "Add"))
        self.editButton.setText(_translate("BaseWindow", "Edit"))
        self.loadButton.setText(_translate("BaseWindow", "Load data"))
        item = self.postWidget.horizontalHeaderItem(1)
        item.setText(_translate("BaseWindow", "ID"))
        item = self.postWidget.horizontalHeaderItem(2)
        item.setText(_translate("BaseWindow", "Tiêu đề"))
        item = self.postWidget.horizontalHeaderItem(3)
        item.setText(_translate("BaseWindow", "Nội dung"))
        item = self.postWidget.horizontalHeaderItem(4)
        item.setText(_translate("BaseWindow", "Url ảnh"))
        self.addImageButton.setText(_translate("BaseWindow", "Add ảnh"))
        self.deleteButton.setText(_translate("BaseWindow", "Delete"))
        self.uploadButton.setText(_translate("BaseWindow", "Up ảnh"))
        self.groupBox.setTitle(_translate("BaseWindow", "Profile"))
        self.editProfileButton.setText(_translate("BaseWindow", "Edit profile"))
        self.saveButton.setText(_translate("BaseWindow", "Save"))
        self.addAvatarButton.setText(_translate("BaseWindow", "Add avata"))
        self.label_9.setText(_translate("BaseWindow", "Phone number"))
        self.label_10.setText(_translate("BaseWindow", "Email"))
        self.label_11.setText(_translate("BaseWindow", "Adrres"))
        self.label_6.setText(_translate("BaseWindow", "Messagers  page"))
        self.groupBox_3.setTitle(_translate("BaseWindow", "GroupBox"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("BaseWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("BaseWindow", "Tiêu đề"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("BaseWindow", "Nội dung"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("BaseWindow", "URL ảnh"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("BaseWindow", "Nền tảng đăng bài"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("BaseWindow", "Trạng thái"))
        self.saveButton_2.setText(_translate("BaseWindow", "Save"))
        self.postButton.setText(_translate("BaseWindow", "Đăng Bài"))
        self.loadDataButton.setText(_translate("BaseWindow", "Load data"))
        self.label_8.setText(_translate("BaseWindow", "Settings page"))
import resources_rc
